const fs=require('node:fs'), path=require('node:path'), assert=require('node:assert/strict')
const backend=path.resolve(process.argv[2],'03_template/medusa-crossborder-base/apps/backend')
require(require.resolve('ts-node',{paths:[backend]})).register({transpileOnly:true,skipProject:true,compilerOptions:{module:'CommonJS',moduleResolution:'Node',target:'ES2020'}})
const {PayPalPaymentProviderService,mapPayPalWebhookAction}=require(backend+'/src/modules/paypal/service.ts')
const {PayPalHttpTransport}=require(backend+'/src/modules/paypal/transport.ts')
const base={session_id:'payses_review',paypal_order_id:'ORDER-A',paypal_authorization_id:'AUTH-A',paypal_capture_id:'CAPTURE-A',amount:'14.99',currency_code:'USD'}
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})
const results=[]
const probe=async(name,fn)=>{try{results.push({name,observed:await fn()})}catch(e){results.push({name,error:e.message})}}
const service=(transport)=>new PayPalPaymentProviderService({},{enabled:true,environment:'sandbox',payment_intent:'AUTHORIZE',transport})
;(async()=>{
await probe('WRONG_ORDER_REJECTED',async()=>{await assert.rejects(service({retrieveOrder:async()=>({order_id:'OTHER',status:'COMPLETED',capture_id:'OTHER',amount:'14.99',currency_code:'USD'})}).getPaymentStatus({data:base}),/different order/);return true})
await probe('MISSING_MONEY_REJECTED',async()=>{await assert.rejects(service({authorizeOrder:async()=>({order_id:'ORDER-A',status:'COMPLETED',authorization_id:'AUTH-A'})}).authorizePayment({data:base}),/trusted amount/);return true})
await probe('NEW_DATA_REFUND_REPLAY_ONCE',async()=>{let calls=0;const s=service({refundCapture:async()=>{calls++;return {refund_id:'REF-A',status:'COMPLETED',amount:'5.00',currency_code:'USD'}}});const a=await s.refundPayment({data:base,amount:5,context:{idempotency_key:'op-a'}});const b=await s.refundPayment({data:a.data,amount:5,context:{idempotency_key:'op-a'}});return {calls,total:b.data.refunded_amount}})
await probe('CONCURRENT_REFUNDS_RETURN_CONFLICTING_TOTALS',async()=>{const s=service({refundCapture:async i=>({refund_id:i.idempotency_key.endsWith('op-a')?'REF-A':'REF-B',status:'COMPLETED',amount:'5.00',currency_code:'USD'})});const values=await Promise.all(['op-a','op-b'].map(key=>s.refundPayment({data:base,amount:5,context:{idempotency_key:key}})));return {totals:values.map(x=>x.data.refunded_amount),note:'provider outputs only; no DB concurrency tested'}})
await probe('CREATE_ORDER_CONTENT_TYPE',async()=>{let contentType;const t=new PayPalHttpTransport({environment:'sandbox',clientId:'fixture',clientSecret:'fixture',fetchImpl:async(url,init)=>{if(url.endsWith('/token'))return json({access_token:'fixture-token',expires_in:300});contentType=new Request(url,init).headers.get('content-type');return json({id:'ORDER-A',status:'CREATED'})}});await t.createOrder({amount:'14.99',currency_code:'USD',intent:'AUTHORIZE',idempotency_key:'test',correlation_id:'payses_review'});return contentType})
await probe('NONRETRYABLE_400_RETRY_COUNT',async()=>{let calls=0;const t=new PayPalHttpTransport({environment:'sandbox',clientId:'fixture',clientSecret:'fixture',fetchImpl:async url=>{if(url.endsWith('/token'))return json({access_token:'fixture-token',expires_in:300});calls++;return json({},400)}});try{await t.retrieveOrder({order_id:'ORDER-A'})}catch{}return calls})
await probe('PENDING_CAPTURE_MAPPED_TO_CAPTURED',async()=>{const t=new PayPalHttpTransport({environment:'sandbox',clientId:'fixture',clientSecret:'fixture',fetchImpl:async url=>url.endsWith('/token')?json({access_token:'fixture-token',expires_in:300}):json({id:'ORDER-A',status:'COMPLETED',purchase_units:[{amount:{value:'14.99',currency_code:'USD'},payments:{captures:[{id:'CAPTURE-A',status:'PENDING',amount:{value:'14.99',currency_code:'USD'}}]}}]})});return (await service(t).getPaymentStatus({data:base})).status})
await probe('WEBHOOK_WITHOUT_EVENT_RESOURCE_ORDER_ID',async()=>mapPayPalWebhookAction({event_type:'PAYMENT.CAPTURE.COMPLETED',resource:{custom_id:'payses_review',amount:{value:'0.01',currency_code:'EUR'}}}).action)
fs.writeFileSync(path.join(__dirname,'payment-probes.json'),JSON.stringify({method:'actual source; fake fetch only; no real transactions',results},null,2));console.log(JSON.stringify(results,null,2))
})().catch(e=>{console.error(e.message);process.exitCode=1})